server:
  port: 8888
  servlet:
    context-path: /demo

spring:
  application:
    name: es
#===========开启切面===========
  aop:
    auto: true
    proxy-target-class: false

elasticsearch:
  host: localhost
  port: 9200

logging:
  config: classpath:logback.xml
  file:
    path: /logs

