server:
  port: 8888
  servlet:
    context-path: /demo

spring:
  profiles:
    active: dev #开发环境
#    active: prod #生产环境
  application:
    name: es
  #===========开启切面===========
  aop:
    auto: true
    proxy-target-class: false

logging:
  config: classpath:logback.xml
  file:
    path: /logs
