#es配置
elasticsearch:
  host: localhost
  port: 9200
#redis配置
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
# mail

  mail:
    host: smtp.163.com
    username: 18621142249@163.com
    password: 123456wangzai
    from: 18621142249@163.com
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true